### ISSUE TITLE
Macro error in runnable.cr:4

### ISSUE THREAD

**Issue by Ragmaanir** [ysbaddaden/minitest.cr#11]
Hi,

i created a project with `crystal init app issue-minitest` and added minitest to the dependencies and when i run the specs i get this error:

```
Error in ./libs/minitest/autorun.cr:9: instantiating 'Minitest:Module#run(Array(String))'

  exit_code = Minitest.run(ARGV)
                       ^~~

in ./libs/minitest/minitest.cr:72: instantiating 'Minitest::Runnable:Class#runnables()'

    suites = Runnable.runnables.shuffle
                      ^~~~~~~~~

in ./libs/minitest/minitest/runnable.cr:4: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
  1. Minitest::Test, Minitest::Spec, Issue::MinitestSpec
--------------------------------------------------------------------------------
Syntax error in expanded macro: macro_85674176:1: unexpected token: EOF

Minitest::Test, Minitest::Spec, Issue::MinitestSpec
                                                   ^

================================================================================

      [self, {{ @type.all_subclasses.join(", ").id }}]

```

I also receive the error in my projects. 

Crystal: 0.17.3
Minitest: master (v0.3.4)

**Comment by ysbaddaden** [comment]
I'm afraid I can't reproduce this. I created a project with Crystal 0.17.3 as you explained, then added Minitest 0.3.4 and modified `spec/spec_helper.cr` to require `minitest/autorun` instead of `spec` and I don't have this error.

**Comment by ysbaddaden** [comment]
The bug comes from using Minitest 0.3.3. Double check that the dependency is correct with: `crystal deps list`. If not you may remove `libs/minitest` then reinstall the dependency with `crystal deps`.

**Comment by Ragmaanir** [comment]
Thanks, silly mistake on my side. My project used a custom fork which was stuck on 0.3.3. Sorry :disappointed:

**Comment by ysbaddaden** [comment]
No problem :)
