### ISSUE TITLE
Set random seed

### ISSUE THREAD

**Issue by splattael** [ysbaddaden/minitest.cr#14]
Hi,

I have random tests failures in one of my projects.

In order to hunt down those random test failures it would awesome to be able to pass a seed via an option or envvar similar to Ruby's [minitest](https://github.com/seattlerb/minitest).

I've found 2 places where `Array#shuffle` is called:
* [src/minitest.cr:72](https://github.com/ysbaddaden/minitest.cr/blob/f0989f73b7725268e98b62360ee215f87d6f708c/src/minitest.cr#L72)
* [src/test.cr:32](https://github.com/ysbaddaden/minitest.cr/blob/f0989f73b7725268e98b62360ee215f87d6f708c/src/test.cr#L32)

I guess, the first occurrence is easy to fix but I am not sure about the macro in the second :fearful: 

@ysbaddaden WDYT about this feature request?

(Bonus: One could port Ruby's [minitest-bisect](https://github.com/seattlerb/minitest-bisect) after this issue is fixed :sunglasses:  )

Kind regards,
  Peter

**Comment by ysbaddaden** [comment]
Yes: b29cccb :)

**Comment by ysbaddaden** [comment]
Can you test and verify it works as expected?

**Comment by splattael** [comment]
@ysbaddaden Awesome, thank you! :green_heart:

I am testing it right now and will report...

**Comment by splattael** [comment]
@ysbaddaden Quick feedback: It's not working for our project although `seed` is passed properly.
I am trying to reproduce this behavior on a smaller project. Stay tuned.

**Comment by splattael** [comment]
@ysbaddaden I was able to reproduce the situation on a fresh project:
https://github.com/splattael/random-failures

**Comment by splattael** [comment]
@ysbaddaden I've just noticed that [Minitest.set_random_seed](https://github.com/ysbaddaden/minitest.cr/blob/master/src/minitest.cr#L133) is never called.

**Comment by splattael** [comment]
@ysbaddaden I fear that the usage of macros at [src/test.cr:32](https://github.com/ysbaddaden/minitest.cr/blob/f0989f73b7725268e98b62360ee215f87d6f708c/src/test.cr#L32) is currently the show-stopper because the order is defined during compile time. At this point, we cannot set the random seed.

**Comment by ysbaddaden** [comment]
I totally misunderstood the `--seed` feature of Minitest. As you state, this isn't possible at this time, without relying on ugly hacks (e.g. hash each method name, ~~sort~~ randomize at runtime using the seed, run tests in the given order).

I'll revert my commits.

**Comment by splattael** [comment]
If you were able to seed `Random::DEFAULT` at compile time - the same way you did at runtime - I would not call it an "ugly hack"; but a feature :sunglasses:

Is it possible it all? I tried and failed :-(

**Comment by ysbaddaden** [comment]
It needs support from the compiler: allow access and reseed of `Random::DEFAULT` from macros.

You may create an issue to ask about this. We have a concrete use-case :-)

**Comment by splattael** [comment]
@ysbaddaden Issue created :smile_cat:

**Comment by ysbaddaden** [comment]
We could indeed use procs. It's more complicated, but it works (I tested it out).

There is another problem, thought: test suites (Runnables) are shuffled, then tests are shuffled for each suite when it's picked up; there is no global array of suite/tests that is shuffled once and for all, then parallel runners would pick one and run it —I understand Ruby's Minitest does that?

Shuffling suites and tests looks like a good idea, so it would be a nice addition, but that requires quite a refactor.

**Comment by splattael** [comment]
Yes, Ruby's minitest first shuffles the suites. Each suite is run (in parallel or serial) their also shuffled runnables methods. 

https://github.com/seattlerb/minitest/blob/c6ba2afd90473b76d289562edd24f7d7ca8484f9/lib/minitest.rb#L110,L118:

```
  #   Minitest.autorun
  #     Minitest.run(args)
  #       Minitest.__run(reporter, options)
  #         Runnable.runnables.each
  #           runnable.run(reporter, options)
  #             self.runnable_methods.each
  #               self.run_one_method(self, runnable_method, reporter)
  #                 Minitest.run_one_method(klass, runnable_method)
  #                   klass.new(runnable_method).run
```

I thought that minitest.cr does exactly the same, no?
(https://github.com/ysbaddaden/minitest.cr/blob/e10ac389de95ab6d6655084556f73d99893a1e20/src/minitest.cr#L72,L87)

**Comment by ysbaddaden** [comment]
Please see #15
