### ISSUE TITLE
Calling a non-existent Time method

### ISSUE THREAD

**Issue by HCLarsen** [ysbaddaden/minitest.cr#25]
I'm using your shard for the first time, and got the following error when running a simple test. The reporter file appears to be calling a method on a Time object that doesn't exist.

```
Error in test/current_weather_test.cr:1: while requiring "minitest/autorun"

require "minitest/autorun"
^

in lib/minitest/src/autorun.cr:9: instantiating 'Minitest:Module#run(Array(String))'

  exit_code = Minitest.run(ARGV)
                       ^~~

in lib/minitest/src/minitest.cr:70: instantiating 'Minitest::AbstractReporter+#start()'

    reporter.start
             ^~~~~

in lib/minitest/src/reporter.cr:92: undefined method 'monotonic' for Time:Class

      @start_time = Time.monotonic
```

**Comment by ysbaddaden** [comment]
You need Crystal 0.24.0.

**Comment by HCLarsen** [comment]
You mean the version of Crystal that all the core contributors are telling us NOT to use?

**Comment by ysbaddaden** [comment]
You can use minitest 0.3.5 if you prefer to stick with crystal 0.23.x.

Minitest 0.3.6 was released for developers that upgraded to crystal 0.24.0 (I did). The fun will come with the next release —which introduces `--seed` and `--chaos` :smiling_imp:
