### ISSUE TITLE
No Assertions Count in Output

### ISSUE THREAD

**Issue by HCLarsen** [ysbaddaden/minitest.cr#26]
Ruby's Minitest gives an output like this:
```
155 runs, 317 assertions, 0 failures, 0 errors, 0 skips
```

But yours gives an output like this:
```
2 tests, 1 failures, 0 errors, 0 skips
```

Since tests aren't always written with one assertion per test, isn't the original format better?

**Comment by ysbaddaden** [comment]
I don't count individual assertions. Do they really matter?

**Comment by HCLarsen** [comment]
I think so. It's always the first thing I look at when I run my Ruby tests. Since they're there in the output from the original Minitest, I'd say I'm probably not along in thinking that they matter.

**Comment by ysbaddaden** [comment]
What I look at is `X failures` and `X errors`. Individual assertions count always felt superfluous and noisy.

**Comment by HCLarsen** [comment]
There's nothing wrong with that. However, I thought you were building this Shard to be as close in functionality to the original Multitest as possible.

**Comment by ysbaddaden** [comment]
Ocerall, yes, but I guess I took a few liberties. That may be the only one, along with the recent `--chaos`.

**Comment by HCLarsen** [comment]
Does that mean you're planning to add a setup method like the Ruby minitest has? I can't find any mention of it in your documentation.

**Comment by felixbuenemann** [comment]
I think counting assertions would be useful. For example currently, if I have assertions against values of a block, I always need to assign to a variable outside the block and assert against that, to make sure the assertions actually ran.

If assertions are counted it's much easier to spot faulty tests that do not assert anything.
