### ISSUE TITLE
Provide an easy way to run just one failing test

### ISSUE THREAD

**Issue by robacarp** [ysbaddaden/minitest.cr#30]
Perhaps this will be counter the philosophy of simplicity, but I've used several test suites which make "Run just this one test" easier than it currently is with minitest.cr.

Some examples in the wild:
- [minitest-focus](https://github.com/seattlerb/minitest-focus) provides a way with a focus statement which precedes test declarations
- rspec allows a syntax like this: `it "works", focus: true do`, and [allows tests to be otherwise tagged for grouping](http://rspec.info/documentation/3.7/rspec-core/RSpec/Core/ExampleGroup.html#it-class_method)
- `crystal spec` produces a runnable command as part of an error which will run just the specific failure, which is easy to copy and paste.

minitest.cr provides an `-n /name/` interface which is pretty close, but if tests are defined with `it "should pass"` the correct invocation is `-n /should_pass/` with an underscore added. Specifying `-n "should pass" will run no tests.

**Comment by ysbaddaden** [comment]
It looks like we could have `focus def test_x` and `it "x", focus: true`:

```crystal
focuses = [] of String

macro focus(definition)
  focuses << {{ definition.name.stringify }}
  {{definition}}
end

macro it(name, focus = false)
  {% if focus %}focus{% end %} def test_{{name.id}}
    ret = {{yield}}
  end
end

focus def test_name
  p :test_name
end

def test_other
  p :test_other
end

it("something", focus: true) do
  p :test_something
end

it("more") do
  p :test_more
end

p focuses

test_name if focuses.includes?("test_name")
test_other if focuses.includes?("test_other")
test_something if focuses.includes?("test_something")
test_more if focuses.includes?("test_more")

# => ["test_name", "test_something"]
# => :test_name
# => :test_something
```
