### ISSUE TITLE
Is it possible to provide a way to explicitly declare the type of a `let`?

### ISSUE THREAD

**Issue by robacarp** [ysbaddaden/minitest.cr#34]
`let` is a nice shortcut for declaring some instance variables, but I find myself needing to do something like this:

```crystal
let(:name) do
   Class.new.tap do |inst|
     inst.action
  end
end
```

Which causes the compiler to complain with a `Can't infer the type of instance variable` message.  My workaround has been:

```crystal
@name : Type?

def name
  @name ||= begin
    Class.new.tap do |inst|
      inst.action
    end
  end
end
```

Is there a better way, or a way to beef up the let macro to provide that?

**Comment by ysbaddaden** [comment]
No. But there was a macro here:
https://github.com/imdrasil/minitest.cr/blob/811257f6fdae802f0d65c0f8bf4cb7385562660c/src/spec.cr#L11

**Comment by robacarp** [comment]
Great, thanks.

**Comment by ysbaddaden** [comment]
5 years later, this is now possible: #49
