### ISSUE TITLE
Handling of "undefined method '+' for Nil (compile-time type is (String | Nil))"

### ISSUE THREAD

**Issue by TomFreudenberg** [ysbaddaden/minitest.cr#43]
I am porting our gem to a crystal shard and for that I am porting the tests, too. Thanks to your minitest shard - it makes it easy most of all.

But I have some condition - I would like to know how to handle.

Let's say I will test some class of my project

#### file: ./lib/midi-smtp-server.cr

```crystal
require "midi-smtp-server/version"

module MidiSmtpServer

  # class for SmtpServer
  class Smtpd
  end

end
```

I include a VERSION module to save traditionally the version

#### file: ./lib/midi-smtp-server/version.cr

```crystal
module MidiSmtpServer

  module VERSION

    MAJOR = 3
    MINOR = 0
    TINY = 1

    STRING = [MAJOR, MINOR, TINY].compact.join(".")

    DATE = "2021-03-12"

  end

end
```

And a simple specs test for that

#### file: ./test/version_test.cr

```crystal
require "minitest/autorun"
require "midi-smtp-server"

describe MidiSmtpServerTest do
  # initialize before tests
  before do
    @str = MidiSmtpServer::VERSION::STRING
  end

  describe "test correct version string" do
    it "must be equal to 3.0.1" do
      assert_equal "3.0.1", @str
    end
  end
end
```

running:

```bash
crystal run test/demo_test.cr -- --verbose
```

will cause this error:

![grafik](https://user-images.githubusercontent.com/410087/112312338-ff436a00-8ca6-11eb-98bd-3e6d839679a1.png)

as read in the crystal documentation (hopefully understand correctly), I set the type inside the version module to:

```crystal
    STRING = [MAJOR, MINOR, TINY].compact.join(".").as(String)
```

and with that the test works as expected:

![grafik](https://user-images.githubusercontent.com/410087/112312815-81cc2980-8ca7-11eb-9b53-5554a1b1b170.png)

<br>

BUT if I want to make a check like:

```crystal
assert_equal "3.0.1[]", @str + "[]"
```

I get this as an error:

![grafik](https://user-images.githubusercontent.com/410087/112313484-2fd7d380-8ca8-11eb-9e85-7494f2b569c5.png)

<br>

Looks like the compiler does not know, that `before` will be called and initialize the variable.

If I move `@str` as `STR` to a global variable in front of the tests like:

```crystal
STR =  MidiSmtpServer::VERSION::STRING
```

then the test of:

```crystal
assert_equal "3.0.1[]", STR + "[]"
```

will be get compiled and run fine.

<br>

Using the `let` macro and test like:

```crystal
let(:str) { MidiSmtpServer::VERSION::STRING }

assert_equal "3.0.1[]", str + "[]"
```

will work - BUT NOT using `str` as instance var

```crystal
let(:str) { MidiSmtpServer::VERSION::STRING }

assert_equal "3.0.1[]", @str + "[]"
```

![grafik](https://user-images.githubusercontent.com/410087/112314881-d40e4a00-8ca9-11eb-9689-9ee4e921afa5.png)

<br>

Any suggestions or ideas?

<br>

Cheers
Tom

P.S. Thanks for your effort and sharing this shard

**Comment by TomFreudenberg** [comment]
If I overload the Specs initialize method and initialize the `@str` as instance var, all is running as expected:

```crystal
describe MidiSmtpServerTest do

  def initialize(@__reporter)
    @str = ""
    super
  end

  # initialize before tests
  before do
    @str = MidiSmtpServer::VERSION::STRING
  end

  describe "test correct version string" do
    it "must be equal to 3.0.1" do
      assert_equal "3.0.1[]", @str + "[]"
    end
  end
end
```

Seems to me like:

@instance_var can't be introduced and initialized in `before` or `let` macro but only in `def initialize`

**Comment by ysbaddaden** [comment]
This is a basic issue: Crystal can't know that `@str` is properly initialized before your test runs, and thus complains. In order to use ivars directly, they must be declared in `#initialize`, otherwise crystal will infer it as a nilable type (`String | Nil`).

With Minitest::Spec you should just use `let(:str) { MidiSmtpServer::VERSION::STRING }` then call `str` when you need it.

If you insist on using the ivar directly, you may use `@str.not_nil!` but that's a code smell and not worth the ugliness.

**Comment by TomFreudenberg** [comment]
Hi Julien @ysbaddaden

thanks for your feedback - got it.

So then I prefer to override the initialize part in case that this is also compatible to the ruby code and I may stay with the same codebase content (mostly)

Cheers
Tom
