### ISSUE TITLE
tests with `:` in the description string generate invalid methods

### ISSUE THREAD

**Issue by robacarp** [ysbaddaden/minitest.cr#46]
This test definition crashes minitest because the macro output isn't a valid function signature:

```crystal
  it "when attr: false" do
    # blah
  end
```

 > 1 |      def test_when_attr:_false
Error: a space is mandatory between ':' and return type
make: *** [test] Error 1

I didn't dig into the test suite to sort out _why_ `:` is included in the [regex whitelist](https://github.com/ysbaddaden/minitest.cr/blob/main/src/spec.cr#L43), but there it is.

**Comment by ysbaddaden** [comment]
This appeared in 1605a3fd4d876d99e1aa00a9375e468fb4bb07a5 and is both for `describe` and `it` and that's because of namespaces: we must preserve `::` but minitest/spec shouldn't allow `:` :facepalm: 

I guess there shouldn't be any `:` or `::` in `it` though, only `describe`.

**Comment by ysbaddaden** [comment]
@robacarp That should be fixed in #47. Please try it and tell me if it fixes your problem.
