### ISSUE TITLE
All tests in a test class should not be run on a single instance of Minitest::Test

### ISSUE THREAD

**Issue by reggieb** [ysbaddaden/minitest.cr#6]
With ruby minitest, each test within a test file, is run on a new instance of the test class. This prevents instance variables set in one test leaking into another test. 

For example, in ruby minitest both of these tests would pass:

```
class MyTest < Minitest::Test

  def test_a
    assert_equal :a, a
    @a = :b
  end

  def test_b
    assert_equal :a, a
    @a = :c
  end

  def a
    @a ||= :a
  end

end
```

With this crystal minitest suite one of the tests will always fail.

I think the issue is to do with the macro [Minitest::Test#run_tests](https://github.com/ysbaddaden/minitest.cr/blob/master/src/minitest/test.cr) being an instance method rather than a class method. 

I believe the process should be:
1. get test class
2. find instance methods starting with "test_"
3. for each test method
   - get a test instance
   - call the test method on the test instance

Rather than the current:
1. get test class
2. get test instance
3. find instance methods starting with "test_"
4. for each test method
   - call the test method on the test instance

**Comment by ysbaddaden** [comment]
Sorry for the very long delay to reply to this. I didn't know about this behavior, which can be a little odd. I didn't know instance variables weren't shared within the same test class. I'm a little puzzled about this, but it may be better, yes.

**Comment by reggieb** [comment]
It's this bit of code that is the problem:

```
macro def run_tests : Nil
      {{
        @type.methods
          .map(&.name.stringify)
          .select(&.starts_with?("test_"))
          .shuffle
          .map { |m| "run_one(#{m}) { #{m.id} }" }
          .join("\n")
          .id
      }}
      nil
 end
```

It's calling run_one on the the same test class instance. If this was ruby, you could implement a dirty fix by adding a class method `run_one`.

```
def self.run_one(method, &process)
  new.run_one(method, &process)
end
```

Then this line:

```
 .map { |m| "run_one(#{m}) { #{m.id} }" }
```

Could be changed to:

```
 .map { |m| "self.class.run_one(#{m}) { #{m.id} }" }
```

That way each test would be run on a new instance of the test class. Longer term, I'd move the process of initiating the test to be a class method, and then have that generate a new instance against which to call run_one.

However, I'm not sure of the best way of doing it in Crystal.
